[project]
name = "questar-streamlit"
version = "0.1.0"
description = "Questar Streamlit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "streamlit>=1.51.0",
]
